## 학습목표
 1. numpy에서 자주 사용되는 함수들을 사용해보기

In [1]:
import numpy as np

#### numpy documentation
 - [numpy 공식 문서 링크](https://www.numpy.org/devdocs/reference/)
 - numpy에서 제공되는 함수등에 대한 문서

In [2]:
x = np.arange(15).reshape(3, 5)
y = np.random.rand(15).reshape(3, 5)
print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.01239669 0.74429877 0.00753532 0.16338263 0.45100937]
 [0.34323502 0.39651805 0.84061297 0.41097722 0.18629307]
 [0.84769576 0.1495619  0.65342685 0.23574152 0.48119935]]


#### 연산 함수
 - add, substract, multiply, divide

In [ ]:
np.add(x, y)

In [ ]:
np.divide(x, y)

In [ ]:
x + y

In [ ]:
x / y

#### 통계 함수
 - 평균, 분산, 중앙, 최대, 최소값 등등 통계 관련된 함수가 내장

In [ ]:
print(y)

In [ ]:
np.mean(y)

In [ ]:
y.mean()

In [ ]:
np.max(y)

In [ ]:
np.argmax(y)

In [ ]:
np.var(y), np.median(y), np.std(y)

#### 집계함수
 - 합계(sum), 누적합계(cumsum) 등등 계산 가능

In [ ]:
y

In [ ]:
np.sum(y, axis=None)

In [ ]:
np.cumsum(y)

#### any, all 함수
 - any: 특정 조건을 만족하는 것이 하나라도 있으면 True, 아니면 False
 - all: 모든 원소가 특정 조건을 만족한다면 True, 아니면 False

In [4]:
z = np.random.randn(10)
print(z)

[-0.76303974 -1.54256581  1.14939426 -0.0355238   0.94899131 -0.06129414
  0.57137454 -0.6554304  -0.67690716  2.14170121]


In [5]:
z > 0

array([False, False,  True, False,  True, False,  True, False, False,
        True])

In [6]:
np.any(z > 0)

True

In [7]:
np.all(z != 0)

True

#### where 함수
 - 조건에 따라 선별적으로 값을 선택 가능
 - 사용 예) 음수인경우는 0, 나머지는 그대로 값을 쓰는 경우

In [ ]:
z = np.random.randn(10)
print(z)

In [ ]:
np.where(z > 0, z, 0)