## 학습목표
 1. linalg 서브모듈 함수 활용여 선형대수 연산하기

In [1]:
import numpy as np

#### np.linalg.inv
 - 역행렬을 구할 때 사용
 - 모든 차원의 값이 같아야 함

In [2]:
x = np.random.rand(3, 3, 3)
print(x)

np.matmul(x, np.linalg.inv(x))
x @ np.linalg.inv(x)

[[[0.84601826 0.71911863 0.40155135]
  [0.77473091 0.15376027 0.06247788]
  [0.67880812 0.96007558 0.10807714]]

 [[0.42779873 0.32757827 0.78610085]
  [0.27056424 0.74201605 0.36107849]
  [0.26871334 0.54686229 0.65798822]]

 [[0.4624333  0.69237421 0.4378386 ]
  [0.23046827 0.21237589 0.87598701]
  [0.71984938 0.0398948  0.572127  ]]]


array([[[ 1.00000000e+00,  2.64794501e-18, -2.56169015e-17],
        [-2.69637341e-18,  1.00000000e+00, -2.71852152e-17],
        [-1.46245454e-16,  1.57390905e-17,  1.00000000e+00]],

       [[ 1.00000000e+00, -3.21914254e-19, -4.59408584e-16],
        [-2.23499079e-16,  1.00000000e+00,  1.39031588e-16],
        [-1.68646711e-16,  8.87220146e-17,  1.00000000e+00]],

       [[ 1.00000000e+00, -5.91608446e-17,  5.96636803e-17],
        [ 6.56673083e-17,  1.00000000e+00,  7.67511303e-19],
        [ 7.90127864e-18, -1.32233184e-17,  1.00000000e+00]]])

#### np.linalg.solve
 - Ax = B 형태의 선형대수식 솔루션을 제공
 - 예제) 호랑이와 홍합의 합 : 25 호랑이 다리와 홍합 다리의 합은 64
   - x + y = 25
   - 2x + 4y = 64
   
 $$\begin{pmatrix} 1 & 1 \\ 2 & 4 \end{pmatrix}\begin{pmatrix} x \\ y \end{pmatrix}= \begin{pmatrix} 25 \\ 64 \end{pmatrix}$$


In [3]:
A = np.array([[1, 1], [2, 4]])
B = np.array([25, 64])

x = np.linalg.solve(A, B)
print(x)

np.allclose(A@x, B)

[18.  7.]


True