In [5]:
import numpy as np
import pandas as pd

In [10]:
print('*')
print('**')
print('***')
print('****')
print('*****')

*
**
***
****
*****


In [29]:
for i in range(12):
    if (i%2==1):
        print(i)

1
3
5
7
9
11


In [ ]:
np.arange

In [ ]:
for i in range(1,10):
    for (i%2==1):
        print(i)

In [117]:
np.arange(1,2)

array([1])

In [90]:
np.arange(2,4)

array([2, 3])

In [92]:
np.arange(4,7)

array([4, 5, 6])

In [151]:
np.arange(7,11)
 

array([ 7,  8,  9, 10])

In [211]:
np.arange(11,16)

array([11, 12, 13, 14, 15])

In [215]:
np.arange(16,22)

array([16, 17, 18, 19, 20, 21])

In [217]:
np.arange(22,29)

array([22, 23, 24, 25, 26, 27, 28])

In [219]:
np.arange(29,37)

array([29, 30, 31, 32, 33, 34, 35, 36])

In [216]:
for i in range(1,100):

    a = np.arange(k,k+k)
    print(a)

[1]
[2 3]
[3 4 5]
[4 5 6 7]
[5 6 7 8 9]
[ 6  7  8  9 10 11]
[ 7  8  9 10 11 12 13]
[ 8  9 10 11 12 13 14 15]
[ 9 10 11 12 13 14 15 16 17]
[10 11 12 13 14 15 16 17 18 19]
[11 12 13 14 15 16 17 18 19 20 21]
[12 13 14 15 16 17 18 19 20 21 22 23]
[13 14 15 16 17 18 19 20 21 22 23 24 25]
[14 15 16 17 18 19 20 21 22 23 24 25 26 27]
[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]
[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31]
[17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33]
[18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35]
[19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]
[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
[21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41]
[22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43]
[23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45]
[24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47]
[25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 

In [7]:

for i in range(1,100):
    a=np.arange(i,i+i)
    print(a)


[1]
[2 3]
[3 4 5]
[4 5 6 7]
[5 6 7 8 9]
[ 6  7  8  9 10 11]
[ 7  8  9 10 11 12 13]
[ 8  9 10 11 12 13 14 15]
[ 9 10 11 12 13 14 15 16 17]
[10 11 12 13 14 15 16 17 18 19]
[11 12 13 14 15 16 17 18 19 20 21]
[12 13 14 15 16 17 18 19 20 21 22 23]
[13 14 15 16 17 18 19 20 21 22 23 24 25]
[14 15 16 17 18 19 20 21 22 23 24 25 26 27]
[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]
[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31]
[17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33]
[18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35]
[19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]
[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
[21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41]
[22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43]
[23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45]
[24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47]
[25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 

In [31]:

for i in range(1, 12):
  a=1
  for j in range(1,i):
    print(a, end = "\t")
    a=int(a*2)
    a=int(a/4)
  for j in range(1,i-1):
    print(a, end = "\t")
    a=int(a/2)
  print()


100	
100	50	25	
100	50	25	12	6	
100	50	25	12	6	3	1	
100	50	25	12	6	3	1	0	0	
100	50	25	12	6	3	1	0	0	0	0	
100	50	25	12	6	3	1	0	0	0	0	0	0	
100	50	25	12	6	3	1	0	0	0	0	0	0	0	0	
100	50	25	12	6	3	1	0	0	0	0	0	0	0	0	0	0	
100	50	25	12	6	3	1	0	0	0	0	0	0	0	0	0	0	0	0	


In [27]:

for i in range(1, 11):
    print("*"*i)

*
**
***
****
*****
******
*******
********
*********
**********


In [34]:

n=1
for i in range(1, 106):

    sum = (n+1)*n // 2

    print(i , end = ' ')

    if(sum == i):

        print()

        n+=1

1 
2 3 
4 5 6 
7 8 9 10 
11 12 13 14 15 
16 17 18 19 20 21 
22 23 24 25 26 27 28 
29 30 31 32 33 34 35 36 
37 38 39 40 41 42 43 44 45 
46 47 48 49 50 51 52 53 54 55 
56 57 58 59 60 61 62 63 64 65 66 
67 68 69 70 71 72 73 74 75 76 77 78 
79 80 81 82 83 84 85 86 87 88 89 90 91 
92 93 94 95 96 97 98 99 100 101 102 103 104 105 


In [35]:


line_number=1       # 줄 번호
output_count=0      # 줄에서의 글자 출력 갯수

for i in range(1, 106):
    print(i , end = ' ')
    output_count+=1

    if(line_number == output_count):
        print()
        line_number+=1
        output_count=0;
    

1 
2 3 
4 5 6 
7 8 9 10 
11 12 13 14 15 
16 17 18 19 20 21 
22 23 24 25 26 27 28 
29 30 31 32 33 34 35 36 
37 38 39 40 41 42 43 44 45 
46 47 48 49 50 51 52 53 54 55 
56 57 58 59 60 61 62 63 64 65 66 
67 68 69 70 71 72 73 74 75 76 77 78 
79 80 81 82 83 84 85 86 87 88 89 90 91 
92 93 94 95 96 97 98 99 100 101 102 103 104 105 


In [16]:

for i in range(1,(5*2)+1):
    if (i<=5):
        for j in range(1, i+1):
            print(j, end='')
        print("")    

1
12
123
1234
12345


In [3]:

for x in range(5):
    for y in range(5):
        if y<=x:
            print(y)
       

0
0
1
0
1
2
0
1
2
3
0
1
2
3
4


In [64]:
x='1'
for x in range(100):
    for y in range(100):
        print(x,y)
       
       


0 0
0 1
0 2
0 3
0 4
0 5
0 6
0 7
0 8
0 9
0 10
0 11
0 12
0 13
0 14
0 15
0 16
0 17
0 18
0 19
0 20
0 21
0 22
0 23
0 24
0 25
0 26
0 27
0 28
0 29
0 30
0 31
0 32
0 33
0 34
0 35
0 36
0 37
0 38
0 39
0 40
0 41
0 42
0 43
0 44
0 45
0 46
0 47
0 48
0 49
0 50
0 51
0 52
0 53
0 54
0 55
0 56
0 57
0 58
0 59
0 60
0 61
0 62
0 63
0 64
0 65
0 66
0 67
0 68
0 69
0 70
0 71
0 72
0 73
0 74
0 75
0 76
0 77
0 78
0 79
0 80
0 81
0 82
0 83
0 84
0 85
0 86
0 87
0 88
0 89
0 90
0 91
0 92
0 93
0 94
0 95
0 96
0 97
0 98
0 99
1 0
1 1
1 2
1 3
1 4
1 5
1 6
1 7
1 8
1 9
1 10
1 11
1 12
1 13
1 14
1 15
1 16
1 17
1 18
1 19
1 20
1 21
1 22
1 23
1 24
1 25
1 26
1 27
1 28
1 29
1 30
1 31
1 32
1 33
1 34
1 35
1 36
1 37
1 38
1 39
1 40
1 41
1 42
1 43
1 44
1 45
1 46
1 47
1 48
1 49
1 50
1 51
1 52
1 53
1 54
1 55
1 56
1 57
1 58
1 59
1 60
1 61
1 62
1 63
1 64
1 65
1 66
1 67
1 68
1 69
1 70
1 71
1 72
1 73
1 74
1 75
1 76
1 77
1 78
1 79
1 80
1 81
1 82
1 83
1 84
1 85
1 86
1 87
1 88
1 89
1 90
1 91
1 92
1 93
1 94
1 95
1 96
1 97
1 98
1 99
2 0
2 1
2 2
2 3
2 4


In [ ]:
visitCount = random.randrange(6)
    list_visitDate = date_exp.dategenerate(visitCount)

In [236]:
list=[range(100)]
list

[range(0, 100)]

In [242]:
for i in range(1,100):
    if (i):
         a=f"{list:}"
         list=np.arange(i,i+i)
         print(a)

[ 99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116
 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134
 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152
 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170
 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188
 189 190 191 192 193 194 195 196 197]
[1]
[2 3]
[3 4 5]
[4 5 6 7]
[5 6 7 8 9]
[ 6  7  8  9 10 11]
[ 7  8  9 10 11 12 13]
[ 8  9 10 11 12 13 14 15]
[ 9 10 11 12 13 14 15 16 17]
[10 11 12 13 14 15 16 17 18 19]
[11 12 13 14 15 16 17 18 19 20 21]
[12 13 14 15 16 17 18 19 20 21 22 23]
[13 14 15 16 17 18 19 20 21 22 23 24 25]
[14 15 16 17 18 19 20 21 22 23 24 25 26 27]
[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]
[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31]
[17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33]
[18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35]
[19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]
[20 

In [248]:
a=np.arange(1,100)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [1]:
val = int(input())

for i in range(10):
    for j in range(10):
        print(val * j + i + 1, end=' ')
    print()

ValueError: invalid literal for int() with base 10: ''

In [246]:
a=np.arange(100)
for i in a:
    if (i):
       a=f"{np.arange(100)*i:}"
       print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106
 108 110 112 114 116 118 120 122 124 126 128 130 132 134 136 138 140 142
 144 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174 176 178
 180 182 184 186 188 190 192 194 196 198]
[  0   3   6   9  12  15  18  21  24  27  30  33  36  39  42  45  48  51
  54  57  60  63  66  69  72  75  78  81  84  87  90  93  96  99 102 105
 108 111 114 117 120 123 126 129 132 135 138 141 144 147 150 153 156 159
 162 165 168 171 174 177 180 183 186 189 192 195 198 201 204 207 210

In [62]:
x='*'
for i in range(100):
    if (i%2==1):
       a=f"{'*'*i:^100}"
       print(a)

                                                 *                                                  
                                                ***                                                 
                                               *****                                                
                                              *******                                               
                                             *********                                              
                                            ***********                                             
                                           *************                                            
                                          ***************                                           
                                         *****************                                          
                                        *******************                                

In [33]:
def main():
    # 필요한 설정값을 설정 파일에서 불러오기
    with open("settings.json", "r") as f:
        settings = json.load(f)
    dataDir = settings["dataDir"] 
    dataExt = settings["dataExt"]
    checkList_filename = settings["checkList_filename"]
    # 프로그램 mode 입력받기
    args = makeArgs()
    # 경로 관련 클래스 초기화
    directory = DirController(dataDir, dataExt)
    # 엑셀베이스 관련 클래스 초기화
    excelBase = ExcelBase(checkList_filename, dataDir)
    # 원하는 파일로 데이터베이스만들기 혹은 있으면 해당 파일 불러오기
    excelBase.load(directory.get_rawDir(), dataExt)
    # 현재 데이터 확인
    excelBase.showStatus()

    if args.mode == "CHK" or args.mode == "PP":
        # 확인모드! 아직 점검하지 않은 파일을 보거나, 결정을 미룬 파일을 다시 보거나!
        # CLI QC 책임자 확인
        excelBase.identify()
        excelBase.doTask(args.mode, directory.get_figDir())
    if args.mode == "EXP":
        # 출력모드! 기존에 있던 폴더 몽땅 날리기
        directory.refreshDir_all()
        excelBase.doExport(
            directory.get_includeDir(),
            directory.get_excludeDir(),
            directory.get_postponedDir(),
        )

In [34]:
import os
from re import A
import subprocess
from natsort import natsorted
import pandas as pd
import keyboard
import subprocess
import psutil
import shutil
import argparse
from tqdm import tqdm

In [35]:
# 필요한 함수 선언


def refresh_dir(file_path):
    if os.path.exists(file_path):
        os.remove(file_path)
    os.makedirs(file_path)


def ensure_dir(file_path):
    if not os.path.exists(file_path):
        os.makedirs(file_path)


def kill(proc_pid):
    process = psutil.Process(proc_pid)
    for proc in process.children(recursive=True):
        proc.kill()
    process.kill()




In [39]:
# 필요한 함수 선언


def refresh_dir(file_path):
    if os.path.exists(file_path):
        os.remove(file_path)
    os.makedirs(file_path)


def ensure_dir(file_path):
    if not os.path.exists(file_path):
        os.makedirs(file_path)


def kill(proc_pid):
    process = psutil.Process(proc_pid)
    for proc in process.children(recursive=True):
        proc.kill()
    process.kill()
    
# 프로그램 용도 1. PDF 보면서 list 정리하기 2. list에 따라 csv 옮겨주기
parser = argparse.ArgumentParser()
parser.add_argument(
    "--mode",
    "-mo",
    required=False,
    default="CHK",
    type=str,
    help="mode: CHK | PP | EXP",
)
args = parser.parse_args()
# 파일 주소
# RAW 폴더를 보고 돌아다니면서
# FIG에 있는 PDF 열고
# Included_checked 아래에 저장하기
dataDir = r"."
figDir = r".\articles"
rawDir = r".\choi_homework"
includeDir = r".\CHK"
excludeDir = r".\EXC"
postponedDir = r".\PP"
dataExt = r"articles.xlsx"
# 파일 목록 열기
# 파일 목록없으면 만들기 # 추후에 결과 출력용 만들 때 그떄 풀어놓기
# 목록 다 만들고 목록 출력용으로 만들어 놓기
#  전체 목록 읽으면서 포함 파일만 따로 보관하기

# 프로그램 용도 1. PDF 보면서 list 정리하기 2. list에 따라 csv 옮겨주기
parser = argparse.ArgumentParser()
parser.add_argument(
    "--mode",
    "-mo",
    required=False,
    default="CHK",
    type=str,
    help="mode: CHK | PP | EXP",
)
args = parser.parse_args()
# 파일 주소
# RAW 폴더를 보고 돌아다니면서
# FIG에 있는 PDF 열고
# Included_checked 아래에 저장하기
dataDir = r"."
figDir = r".\articles"
includeDir = r".\CHK"
excludeDir = r".\EXC"
postponedDir = r".\PP"
dataExt = r"articles.xlsx"
# 파일 목록 열기
# 파일 목록없으면 만들기 # 추후에 결과 출력용 만들 때 그떄 풀어놓기
# 목록 다 만들고 목록 출력용으로 만들어 놓기
#  전체 목록 읽으면서 포함 파일만 따로 보관하기


# 파일 목록 전체 들고오고 필요한 확장자만 고르고 들고온 파일 목록에서 .txt만 남기고 나머지 것들 제외시키기
dataList = natsorted(
    [os.path.join(i[0], i[2][0]) for i in list(os.walk(rawDir)) if ("IMU" in i[0])]
)
excluded_fig = []  # 제외된 경우 1이라고 표기
# 일단 총 개수 알려주기
# 데이터가 어디까지 처리되었는지 확인할 수 있도록 함.
# list_Excluded_byFig.xlsx를 참고해서 어차피 순차적으로 볼 꺼니까 어디까지 봤는지 확인하게 함
# 추후에 안된 것만 따로 돌수있도록 하는 기능 추가하던가..하자

# list_Excluded_byFig.xlsx 가 있으면
# dataList 손보기
# 없으면 만들기
listName = r"CheckList.xlsx"
if os.path.isfile(os.path.join(dataDir, listName)):
    list_Excluded_byFig = pd.read_excel(
        os.path.join(dataDir, listName), engine="openpyxl"
    )
else:
    list_Excluded_byFig = pd.DataFrame(columns=["filename", "type", "note", "checker"])
    list_Excluded_byFig["filename"] = dataList
    list_Excluded_byFig["type"] = "TBD"
# 그냥 시작
print("\n= Type your Name = ")
chk_name = input()
print(f"{chk_name} is entering...")

print("\n== Status ==")
print(list_Excluded_byFig["type"].value_counts())
if "TBD" in list_Excluded_byFig["type"].value_counts():
    num_TBD = list_Excluded_byFig["type"].value_counts()["TBD"]
if "PP" in list_Excluded_byFig["type"].value_counts():
    num_PP = list_Excluded_byFig["type"].value_counts()["PP"]
if args.mode == "EXP":
    print("\n=== EXPORT MODE ===")
    print("now exporting files...")
    # mode가 켜져있으면 list를 기반으로 출력 작업
    # 저장 폴더 만들기
    ensure_dir(includeDir)
    ensure_dir(excludeDir)  # 쓸일이 없네 필요하면
    ensure_dir(postponedDir)  # 쓸일이 없넹 필요하면 넣자

    # list는 이미 불렀음
    # 전체 리스트 순회
    for file in tqdm(list_Excluded_byFig["filename"]):
        basename = os.path.basename(file)
        # type에서 IN이라고 되어 있는 file이 있으면
        if (
            list_Excluded_byFig.loc[list_Excluded_byFig.filename == file, "type"]
            == "IN"
        ).bool():
            # 순회하면서 "IN"인 것만 raw에 저장하기
            if not os.path.exists(
                os.path.join(includeDir, basename)
            ):  # 파일이 이미 있으면 그냥 지나감
                shutil.copyfile(file, os.path.join(includeDir, basename))

        # type에서 IN이라고 되어 있는 file이 있으면
        elif (
            list_Excluded_byFig.loc[list_Excluded_byFig.filename == file, "type"]
            == "EXC"
        ).bool():
            # 순회하면서 "IN"인 것만 raw에 저장하기
            if not os.path.exists(
                os.path.join(excludeDir, basename)
            ):  # 파일이 이미 있으면 그냥 지나감
                shutil.copyfile(file, os.path.join(excludeDir, basename))
        # type에서 IN이라고 되어 있는 file이 있으면
        elif (
            list_Excluded_byFig.loc[list_Excluded_byFig.filename == file, "type"]
            == "PP"
        ).bool():
            # 순회하면서 "IN"인 것만 raw에 저장하기
            if not os.path.exists(
                os.path.join(postponedDir, basename)
            ):  # 파일이 이미 있으면 그냥 지나감
                shutil.copyfile(file, os.path.join(postponedDir, basename))
    print("Done!")

elif args.mode == "CHK":

    # mode가 꺼져있으면 listing 작업
    print("\n=== CHECK MODE ===")
    print("||   KEY - FUNCTION   ||")
    print("|| 'w' - go next file || 'p' - terminate program ||")
    print("|| 'q' - for include  || 'e' - for exclude       ||")
    print("|| 's' - for postpone ||                         ||")
    num_trial = 0
    firstScene = True
    for datum in dataList:
        if (
            list_Excluded_byFig.loc[
                list_Excluded_byFig.filename == datum, "type"
            ].values
            == "TBD"
        ):
            while True:
                if keyboard.read_key(suppress=True) == "w":
                    print(f"\nNo:{num_trial} | remains: {num_TBD-num_trial}")
                    num_trial = num_trial + 1
                    break
                if keyboard.read_key(suppress=True) == "p":  # 제거할 파일
                    print("\nwait for saving the list...")
                    list_Excluded_byFig.to_excel(
                        os.path.join(dataDir, listName), index=False
                    )
                    print("See you!")
                    quit()
            print(f"Target: {datum}")
            basename = basename = os.path.basename(datum)
            plot = subprocess.Popen(
                [
                    os.path.join(
                        figDir,
                        basename.split("_")[0],
                        basename.replace(".xlsx", ".pdf"),
                    )
                ],
                shell=True,
            )
            while True:

                if keyboard.read_key(suppress=True) == "q":  # 포함시킬 파일
                    list_Excluded_byFig.loc[
                        list_Excluded_byFig.filename == datum, "type"
                    ] = "IN"
                    list_Excluded_byFig.loc[
                        list_Excluded_byFig.filename == datum, "checker"
                    ] = chk_name

                    # if not os.path.exists(os.path.join(includeDir,datum)): # 파일이 이미 있으면 그냥 지나감
                    #     shutil.copyfile(os.path.join(rawDir, datum), os.path.join(includeDir,datum))
                    print(f"Included!: {datum}")
                    break
                if keyboard.read_key(suppress=True) == "e":  # 제거할 파일
                    list_Excluded_byFig.loc[
                        list_Excluded_byFig.filename == datum, "type"
                    ] = "EXC"
                    list_Excluded_byFig.loc[
                        list_Excluded_byFig.filename == datum, "checker"
                    ] = chk_name
                    # if not os.path.exists(os.path.join(includeDir,datum)): # 파일이 이미 있으면 그냥 지나감
                    #     shutil.copyfile(os.path.join(rawDir, datum), os.path.join(excludeDir,datum))
                    print(f"Excluded!: {datum}")
                    break
                if keyboard.read_key(suppress=True) == "s":  # 포함시킬 파일
                    list_Excluded_byFig.loc[
                        list_Excluded_byFig.filename == datum, "type"
                    ] = "PP"
                    print("Enter your note:")
                    reason = input()
                    list_Excluded_byFig.loc[
                        list_Excluded_byFig.filename == datum, "note"
                    ] = reason
                    list_Excluded_byFig.loc[
                        list_Excluded_byFig.filename == datum, "checker"
                    ] = chk_name
                    # if not os.path.exists(os.path.join(includeDir,datum)): # 파일이 이미 있으면 그냥 지나감
                    #     shutil.copyfile(os.path.join(rawDir, datum), os.path.join(postpondDir,datum))
                    print(f"Postpond!: {datum}")
                    break

            # https://stackoverflow.com/questions/4789837/how-to-terminate-a-python-subprocess-launched-with-shell-true
            # 덕분에 해결함!
            kill(plot.pid)
            firstScene = False
        # else:
        #     if not firstScene:
        #         print(f'\nPassed: {datum}')
    print("\nThere is no data!")
    print("wait for saving the list...")
    list_Excluded_byFig.to_excel(os.path.join(dataDir, listName), index=False)
    print("See you!")
    quit()

elif args.mode == "PP":
    # mode가 꺼져있으면 listing 작업
    print("\n=== CHECK MODE ===")
    print("||   KEY - FUNCTION   ||")
    print("|| 'w' - go next file || 'p' - terminate program ||")
    print("|| 'q' - for include  || 'e' - for exclude       ||")
    print("|| 'c' - for postpone ||                         ||")
    num_trial = 0
    firstScene = True
    for datum in dataList:
        if (
            list_Excluded_byFig.loc[
                list_Excluded_byFig.filename == datum, "type"
            ].values
            == "PP"
        ):
            while True:
                if keyboard.read_key(suppress=True) == "w":
                    print(f"\nNo:{num_trial} | remains: {num_PP-num_trial}")
                    num_trial = num_trial + 1
                    break
                if keyboard.read_key(suppress=True) == "p":  # 제거할 파일
                    print("\nwait for saving the list...")
                    list_Excluded_byFig.to_excel(
                        os.path.join(dataDir, listName), index=False
                    )
                    print("See you!")
                    quit()
            print(f"Target: {datum}")
            basename = basename = os.path.basename(datum)
            plot = subprocess.Popen(
                [
                    os.path.join(
                        figDir,
                        basename.split("_")[0],
                        basename.replace(".xlsx", ".pdf"),
                    )
                ],
                shell=True,
            )
            while True:

                if keyboard.read_key(suppress=True) == "q":  # 포함시킬 파일
                    list_Excluded_byFig.loc[
                        list_Excluded_byFig.filename == datum, "type"
                    ] = "IN"
                    list_Excluded_byFig.loc[
                        list_Excluded_byFig.filename == datum, "checker"
                    ] = chk_name

                    # if not os.path.exists(os.path.join(includeDir,datum)): # 파일이 이미 있으면 그냥 지나감
                    #     shutil.copyfile(os.path.join(rawDir, datum), os.path.join(includeDir,datum))
                    print(f"Included!: {datum}")
                    break
                if keyboard.read_key(suppress=True) == "e":  # 제거할 파일
                    list_Excluded_byFig.loc[
                        list_Excluded_byFig.filename == datum, "type"
                    ] = "EXC"
                    list_Excluded_byFig.loc[
                        list_Excluded_byFig.filename == datum, "checker"
                    ] = chk_name
                    # if not os.path.exists(os.path.join(includeDir,datum)): # 파일이 이미 있으면 그냥 지나감
                    #     shutil.copyfile(os.path.join(rawDir, datum), os.path.join(excludeDir,datum))
                    print(f"Excluded!: {datum}")
                    break
                if keyboard.read_key(suppress=True) == "s":  # 포함시킬 파일
                    list_Excluded_byFig.loc[
                        list_Excluded_byFig.filename == datum, "type"
                    ] = "PP"
                    print("Enter your note:")
                    reason = input()
                    list_Excluded_byFig.loc[
                        list_Excluded_byFig.filename == datum, "note"
                    ] = reason
                    list_Excluded_byFig.loc[
                        list_Excluded_byFig.filename == datum, "checker"
                    ] = chk_name
                    # if not os.path.exists(os.path.join(includeDir,datum)): # 파일이 이미 있으면 그냥 지나감
                    #     shutil.copyfile(os.path.join(rawDir, datum), os.path.join(postpondDir,datum))
                    print(f"Postpond!: {datum}")
                    break

            # https://stackoverflow.com/questions/4789837/how-to-terminate-a-python-subprocess-launched-with-shell-true
            # 덕분에 해결함!
            kill(plot.pid)
            firstScene = False
    print("\nThere is no data!")
    print("wait for saving the list...")
    list_Excluded_byFig.to_excel(os.path.join(dataDir, listName), index=False)
    print("See you!")
    quit()


usage: ipykernel_launcher.py [-h] [--mode MODE]
ipykernel_launcher.py: error: unrecognized arguments: --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"8422bf7d-573a-400e-a213-4beaa1f59636" --shell=9002 --transport="tcp" --iopub=9004 --f=c:\Users\cwchoi\AppData\Roaming\jupyter\runtime\kernel-15744ASrgKwdcALUD.json


SystemExit: 2

In [40]:
# 프로그램 용도 1. PDF 보면서 list 정리하기 2. list에 따라 csv 옮겨주기
parser = argparse.ArgumentParser()
parser.add_argument(
    "--mode",
    "-mo",
    required=False,
    default="CHK",
    type=str,
    help="mode: CHK | PP | EXP",
)
args = parser.parse_args()
# 파일 주소
# RAW 폴더를 보고 돌아다니면서
# FIG에 있는 PDF 열고
# Included_checked 아래에 저장하기
dataDir = r"."
figDir = r".\articles"
includeDir = r".\CHK"
excludeDir = r".\EXC"
postponedDir = r".\PP"
dataExt = r"articles.xlsx"
# 파일 목록 열기
# 파일 목록없으면 만들기 # 추후에 결과 출력용 만들 때 그떄 풀어놓기
# 목록 다 만들고 목록 출력용으로 만들어 놓기
#  전체 목록 읽으면서 포함 파일만 따로 보관하기


# 파일 목록 전체 들고오고 필요한 확장자만 고르고 들고온 파일 목록에서 .txt만 남기고 나머지 것들 제외시키기
dataList = natsorted(
    [os.path.join(i[0], i[2][0]) for i in list(os.walk(rawDir)) if ("IMU" in i[0])]
)
excluded_fig = []  # 제외된 경우 1이라고 표기
# 일단 총 개수 알려주기
# 데이터가 어디까지 처리되었는지 확인할 수 있도록 함.
# list_Excluded_byFig.xlsx를 참고해서 어차피 순차적으로 볼 꺼니까 어디까지 봤는지 확인하게 함
# 추후에 안된 것만 따로 돌수있도록 하는 기능 추가하던가..하자

# list_Excluded_byFig.xlsx 가 있으면
# dataList 손보기
# 없으면 만들기
listName = r"CheckList.xlsx"
if os.path.isfile(os.path.join(dataDir, listName)):
    list_Excluded_byFig = pd.read_excel(
        os.path.join(dataDir, listName), engine="openpyxl"
    )
else:
    list_Excluded_byFig = pd.DataFrame(columns=["filename", "type", "note", "checker"])
    list_Excluded_byFig["filename"] = dataList
    list_Excluded_byFig["type"] = "TBD"
# 그냥 시작
print("\n= Type your Name = ")
chk_name = input()
print(f"{chk_name} is entering...")

print("\n== Status ==")
print(list_Excluded_byFig["type"].value_counts())
if "TBD" in list_Excluded_byFig["type"].value_counts():
    num_TBD = list_Excluded_byFig["type"].value_counts()["TBD"]
if "PP" in list_Excluded_byFig["type"].value_counts():
    num_PP = list_Excluded_byFig["type"].value_counts()["PP"]
if args.mode == "EXP":
    print("\n=== EXPORT MODE ===")
    print("now exporting files...")
    # mode가 켜져있으면 list를 기반으로 출력 작업
    # 저장 폴더 만들기
    ensure_dir(includeDir)
    ensure_dir(excludeDir)  # 쓸일이 없네 필요하면
    ensure_dir(postponedDir)  # 쓸일이 없넹 필요하면 넣자

    # list는 이미 불렀음
    # 전체 리스트 순회
    for file in tqdm(list_Excluded_byFig["filename"]):
        basename = os.path.basename(file)
        # type에서 IN이라고 되어 있는 file이 있으면
        if (
            list_Excluded_byFig.loc[list_Excluded_byFig.filename == file, "type"]
            == "IN"
        ).bool():
            # 순회하면서 "IN"인 것만 raw에 저장하기
            if not os.path.exists(
                os.path.join(includeDir, basename)
            ):  # 파일이 이미 있으면 그냥 지나감
                shutil.copyfile(file, os.path.join(includeDir, basename))

        # type에서 IN이라고 되어 있는 file이 있으면
        elif (
            list_Excluded_byFig.loc[list_Excluded_byFig.filename == file, "type"]
            == "EXC"
        ).bool():
            # 순회하면서 "IN"인 것만 raw에 저장하기
            if not os.path.exists(
                os.path.join(excludeDir, basename)
            ):  # 파일이 이미 있으면 그냥 지나감
                shutil.copyfile(file, os.path.join(excludeDir, basename))
        # type에서 IN이라고 되어 있는 file이 있으면
        elif (
            list_Excluded_byFig.loc[list_Excluded_byFig.filename == file, "type"]
            == "PP"
        ).bool():
            # 순회하면서 "IN"인 것만 raw에 저장하기
            if not os.path.exists(
                os.path.join(postponedDir, basename)
            ):  # 파일이 이미 있으면 그냥 지나감
                shutil.copyfile(file, os.path.join(postponedDir, basename))
    print("Done!")

elif args.mode == "CHK":

    # mode가 꺼져있으면 listing 작업
    print("\n=== CHECK MODE ===")
    print("||   KEY - FUNCTION   ||")
    print("|| 'w' - go next file || 'p' - terminate program ||")
    print("|| 'q' - for include  || 'e' - for exclude       ||")
    print("|| 's' - for postpone ||                         ||")
    num_trial = 0
    firstScene = True
    for datum in dataList:
        if (
            list_Excluded_byFig.loc[
                list_Excluded_byFig.filename == datum, "type"
            ].values
            == "TBD"
        ):
            while True:
                if keyboard.read_key(suppress=True) == "w":
                    print(f"\nNo:{num_trial} | remains: {num_TBD-num_trial}")
                    num_trial = num_trial + 1
                    break
                if keyboard.read_key(suppress=True) == "p":  # 제거할 파일
                    print("\nwait for saving the list...")
                    list_Excluded_byFig.to_excel(
                        os.path.join(dataDir, listName), index=False
                    )
                    print("See you!")
                    quit()
            print(f"Target: {datum}")
            basename = basename = os.path.basename(datum)
            plot = subprocess.Popen(
                [
                    os.path.join(
                        figDir,
                        basename.split("_")[0],
                        basename.replace(".xlsx", ".pdf"),
                    )
                ],
                shell=True,
            )
            while True:

                if keyboard.read_key(suppress=True) == "q":  # 포함시킬 파일
                    list_Excluded_byFig.loc[
                        list_Excluded_byFig.filename == datum, "type"
                    ] = "IN"
                    list_Excluded_byFig.loc[
                        list_Excluded_byFig.filename == datum, "checker"
                    ] = chk_name

                    # if not os.path.exists(os.path.join(includeDir,datum)): # 파일이 이미 있으면 그냥 지나감
                    #     shutil.copyfile(os.path.join(rawDir, datum), os.path.join(includeDir,datum))
                    print(f"Included!: {datum}")
                    break
                if keyboard.read_key(suppress=True) == "e":  # 제거할 파일
                    list_Excluded_byFig.loc[
                        list_Excluded_byFig.filename == datum, "type"
                    ] = "EXC"
                    list_Excluded_byFig.loc[
                        list_Excluded_byFig.filename == datum, "checker"
                    ] = chk_name
                    # if not os.path.exists(os.path.join(includeDir,datum)): # 파일이 이미 있으면 그냥 지나감
                    #     shutil.copyfile(os.path.join(rawDir, datum), os.path.join(excludeDir,datum))
                    print(f"Excluded!: {datum}")
                    break
                if keyboard.read_key(suppress=True) == "s":  # 포함시킬 파일
                    list_Excluded_byFig.loc[
                        list_Excluded_byFig.filename == datum, "type"
                    ] = "PP"
                    print("Enter your note:")
                    reason = input()
                    list_Excluded_byFig.loc[
                        list_Excluded_byFig.filename == datum, "note"
                    ] = reason
                    list_Excluded_byFig.loc[
                        list_Excluded_byFig.filename == datum, "checker"
                    ] = chk_name
                    # if not os.path.exists(os.path.join(includeDir,datum)): # 파일이 이미 있으면 그냥 지나감
                    #     shutil.copyfile(os.path.join(rawDir, datum), os.path.join(postpondDir,datum))
                    print(f"Postpond!: {datum}")
                    break

            # https://stackoverflow.com/questions/4789837/how-to-terminate-a-python-subprocess-launched-with-shell-true
            # 덕분에 해결함!
            kill(plot.pid)
            firstScene = False
        # else:
        #     if not firstScene:
        #         print(f'\nPassed: {datum}')
    print("\nThere is no data!")
    print("wait for saving the list...")
    list_Excluded_byFig.to_excel(os.path.join(dataDir, listName), index=False)
    print("See you!")
    quit()

elif args.mode == "PP":
    # mode가 꺼져있으면 listing 작업
    print("\n=== CHECK MODE ===")
    print("||   KEY - FUNCTION   ||")
    print("|| 'w' - go next file || 'p' - terminate program ||")
    print("|| 'q' - for include  || 'e' - for exclude       ||")
    print("|| 'c' - for postpone ||                         ||")
    num_trial = 0
    firstScene = True
    for datum in dataList:
        if (
            list_Excluded_byFig.loc[
                list_Excluded_byFig.filename == datum, "type"
            ].values
            == "PP"
        ):
            while True:
                if keyboard.read_key(suppress=True) == "w":
                    print(f"\nNo:{num_trial} | remains: {num_PP-num_trial}")
                    num_trial = num_trial + 1
                    break
                if keyboard.read_key(suppress=True) == "p":  # 제거할 파일
                    print("\nwait for saving the list...")
                    list_Excluded_byFig.to_excel(
                        os.path.join(dataDir, listName), index=False
                    )
                    print("See you!")
                    quit()
            print(f"Target: {datum}")
            basename = basename = os.path.basename(datum)
            plot = subprocess.Popen(
                [
                    os.path.join(
                        figDir,
                        basename.split("_")[0],
                        basename.replace(".xlsx", ".pdf"),
                    )
                ],
                shell=True,
            )
            while True:

                if keyboard.read_key(suppress=True) == "q":  # 포함시킬 파일
                    list_Excluded_byFig.loc[
                        list_Excluded_byFig.filename == datum, "type"
                    ] = "IN"
                    list_Excluded_byFig.loc[
                        list_Excluded_byFig.filename == datum, "checker"
                    ] = chk_name

                    # if not os.path.exists(os.path.join(includeDir,datum)): # 파일이 이미 있으면 그냥 지나감
                    #     shutil.copyfile(os.path.join(rawDir, datum), os.path.join(includeDir,datum))
                    print(f"Included!: {datum}")
                    break
                if keyboard.read_key(suppress=True) == "e":  # 제거할 파일
                    list_Excluded_byFig.loc[
                        list_Excluded_byFig.filename == datum, "type"
                    ] = "EXC"
                    list_Excluded_byFig.loc[
                        list_Excluded_byFig.filename == datum, "checker"
                    ] = chk_name
                    # if not os.path.exists(os.path.join(includeDir,datum)): # 파일이 이미 있으면 그냥 지나감
                    #     shutil.copyfile(os.path.join(rawDir, datum), os.path.join(excludeDir,datum))
                    print(f"Excluded!: {datum}")
                    break
                if keyboard.read_key(suppress=True) == "s":  # 포함시킬 파일
                    list_Excluded_byFig.loc[
                        list_Excluded_byFig.filename == datum, "type"
                    ] = "PP"
                    print("Enter your note:")
                    reason = input()
                    list_Excluded_byFig.loc[
                        list_Excluded_byFig.filename == datum, "note"
                    ] = reason
                    list_Excluded_byFig.loc[
                        list_Excluded_byFig.filename == datum, "checker"
                    ] = chk_name
                    # if not os.path.exists(os.path.join(includeDir,datum)): # 파일이 이미 있으면 그냥 지나감
                    #     shutil.copyfile(os.path.join(rawDir, datum), os.path.join(postpondDir,datum))
                    print(f"Postpond!: {datum}")
                    break

            # https://stackoverflow.com/questions/4789837/how-to-terminate-a-python-subprocess-launched-with-shell-true
            # 덕분에 해결함!
            kill(plot.pid)
            firstScene = False
    print("\nThere is no data!")
    print("wait for saving the list...")
    list_Excluded_byFig.to_excel(os.path.join(dataDir, listName), index=False)
    print("See you!")
    quit()


usage: ipykernel_launcher.py [-h] [--mode MODE]
ipykernel_launcher.py: error: unrecognized arguments: --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"8422bf7d-573a-400e-a213-4beaa1f59636" --shell=9002 --transport="tcp" --iopub=9004 --f=c:\Users\cwchoi\AppData\Roaming\jupyter\runtime\kernel-15744ASrgKwdcALUD.json


SystemExit: 2