### 학습목표
 1. 인덱싱과 슬라이싱 활용하기


In [1]:
import numpy as np

#### 인덱싱
 - 파이썬 리스트와 동일한 개념으로 사용
 - ,를 사용하여 각 차원의 인덱스에 접근 가능

 * 1차원 벡터 인덱싱

In [2]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
x[3] = 100
print(x)

[  0   1   2 100   4   5   6   7   8   9]


* 2차원 행렬 인덱싱

In [4]:
x = np.arange(10).reshape(2, 5)
print(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [5]:
x[1,-1]

9

In [ ]:
x[0]

* 3차원 텐서 인덱싱

In [ ]:
x = np.arange(36).reshape(3, 4, 3)
print(x)

In [ ]:
x[1]

#### 슬라이싱
 - 리스트, 문자열 slicing과 동일한 개념으로 사용
 - ,를 사용하여 각 차원 별로 슬라이싱 가능

* 1차원 벡터 슬라이싱

In [ ]:
x = np.arange(10)
print(x)

In [ ]:
x[1:]

* 2차원 행렬 슬라이싱

In [6]:
x = np.arange(10).reshape(2, 5)
print(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [7]:
x[0, :2]

array([0, 1])

In [8]:
x[:1, :2]

array([[0, 1]])

* 3차원 텐서 슬라이싱

In [ ]:
x = np.arange(54).reshape(2, 9, 3)
print(x)

In [ ]:
x[:1, :2, :]

In [ ]:
x[0, :2, :]