## 학습목표
 1. numpy에서 자주 사용되는 함수들을 사용해보기

In [1]:
import numpy as np

#### numpy documentation
 - [numpy 공식 문서 링크](https://www.numpy.org/devdocs/reference/)
 - numpy에서 제공되는 함수등에 대한 문서

In [3]:
x = np.arange(15).reshape(3, 5)
y = np.random.rand(15).reshape(3, 5)
print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.94905088 0.49512899 0.32591638 0.36567537 0.75172984]
 [0.3726853  0.43738442 0.3712619  0.8858132  0.52467523]
 [0.93047625 0.97293845 0.79531538 0.69799154 0.16346575]]


#### 연산 함수
 - add, substract, multiply, divide

In [4]:
np.add(x,y)

array([[ 0.94905088,  1.49512899,  2.32591638,  3.36567537,  4.75172984],
       [ 5.3726853 ,  6.43738442,  7.3712619 ,  8.8858132 ,  9.52467523],
       [10.93047625, 11.97293845, 12.79531538, 13.69799154, 14.16346575]])

#### 통계 함수
 - 평균, 분산, 중앙, 최대, 최소값 등등 통계 관련된 함수가 내장

In [5]:
print(y)

[[0.94905088 0.49512899 0.32591638 0.36567537 0.75172984]
 [0.3726853  0.43738442 0.3712619  0.8858132  0.52467523]
 [0.93047625 0.97293845 0.79531538 0.69799154 0.16346575]]


In [6]:
np.mean(y)

0.6026339257090071

In [7]:
np.argmax(y)

11

#### 집계함수
 - 합계(sum), 누적합계(cumsum) 등등 계산 가능

In [8]:
y

array([[0.94905088, 0.49512899, 0.32591638, 0.36567537, 0.75172984],
       [0.3726853 , 0.43738442, 0.3712619 , 0.8858132 , 0.52467523],
       [0.93047625, 0.97293845, 0.79531538, 0.69799154, 0.16346575]])

In [9]:
np.sum(y, axis=None)

9.039508885635106

In [10]:
np.cumsum(y)

array([0.94905088, 1.44417987, 1.77009625, 2.13577162, 2.88750146,
       3.26018676, 3.69757119, 4.06883308, 4.95464628, 5.47932151,
       6.40979776, 7.38273622, 8.17805159, 8.87604313, 9.03950889])

#### any, all 함수
 - any: 특정 조건을 만족하는 것이 하나라도 있으면 True, 아니면 False
 - all: 모든 원소가 특정 조건을 만족한다면 True, 아니면 False

In [11]:
np.std(np.arange(1, 5))

1.118033988749895

#### where 함수
 - 조건에 따라 선별적으로 값을 선택 가능
 - 사용 예) 음수인경우는 0, 나머지는 그대로 값을 쓰는 경우

In [12]:
z = np.random.randn(10)
print(z)

[ 0.45868255 -0.68538172 -0.29983433 -0.42436512 -0.08206043 -0.31116027
  0.48756147  0.99070876  0.74313192 -0.40330916]


In [13]:
np.where(z > 0, z, 0)

array([0.45868255, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.48756147, 0.99070876, 0.74313192, 0.        ])