## 학습목표
 1. linalg 서브모듈 함수 활용여 선형대수 연산하기

In [1]:
import numpy as np

#### np.linalg.inv
 - 역행렬을 구할 때 사용
 - 모든 차원의 값이 같아야 함

In [17]:
x = np.random.randint(1, 100, size = 27).reshape(3,3,3)
print(x)

np.matmul(x, np.linalg.inv(x))
x @ np.linalg.inv(x)

[[[45  4 43]
  [21 44 86]
  [ 2 91  1]]

 [[76 24 29]
  [11 23 49]
  [45 50 76]]

 [[72 30 98]
  [60 49 96]
  [71 69 84]]]


array([[[ 1.00000000e+00,  3.46944695e-17,  1.90819582e-17],
        [ 1.16226473e-16,  1.00000000e+00,  3.81639165e-17],
        [ 4.33680869e-18,  0.00000000e+00,  1.00000000e+00]],

       [[ 1.00000000e+00,  1.94289029e-16, -1.24900090e-16],
        [-1.21430643e-16,  1.00000000e+00,  2.63677968e-16],
        [-1.24900090e-16,  9.99200722e-16,  1.00000000e+00]],

       [[ 1.00000000e+00,  4.44089210e-16, -1.59594560e-16],
        [ 3.33066907e-16,  1.00000000e+00, -1.11022302e-16],
        [ 9.71445147e-17, -4.44089210e-16,  1.00000000e+00]]])

#### np.linalg.solve
 - Ax = B 형태의 선형대수식 솔루션을 제공
 - 예제) 호랑이와 홍합의 합 : 25 호랑이 다리와 홍합 다리의 합은 64
   - x + y = 25
   - 2x + 4y = 64
   
 $$\begin{pmatrix} 1 & 1 \\ 2 & 4 \end{pmatrix}\begin{pmatrix} x \\ y \end{pmatrix}= \begin{pmatrix} 25 \\ 64 \end{pmatrix}$$


In [18]:
A = np.array([[1,1], [2,4]])
B = np.array([25, 64])

x = np.linalg.solve(A,B)
print(x)

np.allclose(A@x,B)

[18.  7.]


True