### 학습목표
 - random 서브모듈 함수를 통해 ndarray 생성하기

In [1]:
import numpy as np

#### random 서브모듈

#### rand 함수
 - 0, 1사이의 분포로 랜덤한 ndarray 생성

In [2]:
np.random.rand(4, 5, 3)

array([[[0.54349198, 0.72963429, 0.99987176],
        [0.1301488 , 0.58791195, 0.04191671],
        [0.97438514, 0.94136486, 0.55763399],
        [0.76026762, 0.53250756, 0.3305542 ],
        [0.51268353, 0.50689865, 0.56127327]],

       [[0.61070872, 0.83815306, 0.31140037],
        [0.2052414 , 0.03544966, 0.05726119],
        [0.16799611, 0.37523517, 0.77032626],
        [0.33130053, 0.20107997, 0.61333047],
        [0.60225846, 0.22625895, 0.54215653]],

       [[0.60961703, 0.31315568, 0.19887582],
        [0.5573035 , 0.71268573, 0.90700023],
        [0.15866425, 0.81228037, 0.79067592],
        [0.48420959, 0.8292429 , 0.39073201],
        [0.78150973, 0.6530219 , 0.36277089]],

       [[0.87884004, 0.50316794, 0.66376144],
        [0.13267441, 0.81617125, 0.5650417 ],
        [0.17086762, 0.07976871, 0.11245138],
        [0.48815229, 0.57835855, 0.83943813],
        [0.49041303, 0.15568559, 0.1673499 ]]])

#### randn함수
 - n: normal distribution(정규분포)
 - 정규분포로 샘플링된 랜덤 ndarray 생성

In [3]:
np.random.randn(5)

array([-1.28645487,  0.38295023,  1.15184473,  1.8857662 , -0.66394348])

In [4]:
np.random.randn(3, 4, 2)

array([[[ 0.63298928, -0.49071043],
        [-0.64890213,  0.3401324 ],
        [-1.76079048, -0.48533164],
        [ 0.63136245, -0.02235803]],

       [[-0.36380289, -0.21941157],
        [ 1.68218592, -0.67820058],
        [ 1.69320333,  0.51122234],
        [ 1.56399072,  0.8618275 ]],

       [[ 0.25643644,  0.36326538],
        [-0.37998371,  0.12731317],
        [-0.13098425, -0.53652187],
        [-1.13615347,  0.90036061]]])

#### randint 함수
 - 특정 정수 사이에서 랜덤하게 샘플링

In [5]:
np.random.randint(1, 100, size=(5,))

array([55, 96, 87, 30, 33])

#### seed 함수
 - 랜덤한 값을 동일하게 다시 생성하고자 할때 사용

In [6]:
np.random.seed(23)
np.random.randn(3, 4)

array([[ 0.66698806,  0.02581308, -0.77761941,  0.94863382],
       [ 0.70167179, -1.05108156, -0.36754812, -1.13745969],
       [-1.32214752,  1.77225828, -0.34745899,  0.67014016]])

#### choice
 - 주어진 1차원 ndarray로 부터 랜덤으로 샘플링
 - 정수가 주어진 경우, np.arange(해당숫자)로 간주

In [ ]:
np.random.choice(100, (3, 4))

In [27]:
x = np.array(['Port','Urg', 'Kor', 'Gan'])
np.random.choice(x,size=(2,1),replace=False)

array([['Urg'],
       ['Kor']], dtype='<U4')

#### 확률분포에 따른 ndarray 생성
 - uniform
 - normal 등등

In [28]:
np.random.uniform(1.0, 3.0, size=(4, 5))

array([[1.22128512, 2.40958431, 1.05439985, 1.379564  , 2.54240932],
       [2.5573027 , 2.94196971, 1.82510056, 2.5916267 , 1.93742182],
       [1.88593103, 1.75466492, 2.64655725, 2.12971136, 1.27995792],
       [2.93181904, 1.06233515, 2.85689372, 2.04469465, 1.08750677]])

In [29]:
np.random.normal(size=(3, 4))
np.random.randn(3, 4)

array([[-0.68372991,  1.06662477,  0.11873147, -0.91926775],
       [-0.88268061,  1.08068669,  1.18876308, -0.00780905],
       [-0.76126315,  1.16078548,  1.98861057,  0.55124082]])