## 학습목표
 1. 브로드캐스팅의 이해

In [5]:
import numpy as np

#### 브로드캐스팅
  - Shape이 같은 두 ndarray에 대한 연산은 각 원소별로 진행
  - 연산되는 두 ndarray가 다른 Shape을 갖는 경우 브로드 캐스팅(Shape을 맞춤) 후 진행
    
    


#### 브로드캐스팅 Rule
 - [공식문서](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html#general-broadcasting-rules)
 - 뒷 차원에서 부터 비교하여 Shape이 같거나, 차원 중 값이 1인 것이 존재하면 가능

![브로드캐스팅 예](https://www.tutorialspoint.com/numpy/images/array.jpg)
    - 출처: https://www.tutorialspoint.com/numpy/images/array.jpg 

* Shape이 같은 경우의 연산

In [7]:
x = np.arange(15).reshape(3,5)
y = np.random.rand(15).reshape(3,5)
print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.10103296 0.39715087 0.2071755  0.84303016 0.0761412 ]
 [0.23566532 0.07504578 0.06295709 0.24973392 0.81782465]
 [0.63541982 0.79491994 0.25552649 0.98565146 0.20978859]]


In [8]:
x*y

array([[ 0.        ,  0.39715087,  0.41435099,  2.52909049,  0.30456479],
       [ 1.17832659,  0.45027467,  0.44069961,  1.99787139,  7.36042184],
       [ 6.3541982 ,  8.74411937,  3.06631792, 12.81346901,  2.93704029]])

* Scalar(상수)와의 연산

In [9]:
x % 2 == 0

array([[ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True]])

* Shape이 다른 경우 연산

In [17]:
a = np.arange(12).reshape(4, 3)
print(a)
b = np.arange(100, 103)
print(b)
c = np.arange(1000, 1004)
print(c)
d = b.reshape(1, 3)
print(d)


print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)
print(d)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[100 101 102]
[1000 1001 1002 1003]
[[100 101 102]]
(4, 3)
(3,)
(4,)
(1, 3)
[[100 101 102]]


In [18]:
a+b

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])

In [20]:
a + c

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [21]:
a + d

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])