## 학습목표
1. boolean indexing의 이해

#### Boolean indexing
  - ndarry 인덱싱 시, bool 리스트를 전달하여 True인 경우만 필터링

* 브로드캐스팅을 활용하여 ndarray로 부터 bool list 얻기
 - 예) 짝수인 경우만 찾아보기

In [1]:
import numpy as np

- bool 리스트를 인덱스로 전달

In [3]:
x = np.random.randint(1, 100, size = 10)
print(x)

[19 70 87 29 93 79 62 83 42 38]


In [4]:
even = x % 2 == 0
print(even)

[False  True False False False False  True False  True  True]


In [14]:
y = x[even]
print(y)

[70 62 42 38]


In [13]:
y[y > 50]

array([70, 62])

####  다중조건 사용하기
 - 파이썬 논리 연산지인 and, or, not 키워드 사용 불가
 - & - AND 
 - | - OR 

In [15]:
x % 2 == 0
x < 30

x[(x % 2 == 0) & (x < 30)]

array([], dtype=int32)

In [20]:
x < 30
x > 50

x[(x < 30) | (x > 50)]

array([19, 70, 87, 29, 93, 79, 62, 83])

#### 예제) 2019년 7월 서울 평균기온 데이터
 - 평균기온이 25도를 넘는 날수는?
 - 평균기온이 25를 넘는 날의 평균 기온은?

In [21]:
temp = np.array(
        [23.9, 24.4, 24.1, 25.4, 27.6, 29.7,
         26.7, 25.1, 25.0, 22.7, 21.9, 23.6, 
         24.9, 25.9, 23.8, 24.7, 25.6, 26.9, 
         28.6, 28.0, 25.1, 26.7, 28.1, 26.5, 
         26.3, 25.9, 28.4, 26.1, 27.5, 28.1, 25.8])

In [22]:
len(temp)

31

In [23]:
len(temp[temp > 25.0])

21

In [24]:
np.sum(temp > 25.0)

21

In [25]:
np.mean(temp[temp > 25.0])

26.857142857142858